version: '3'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    healthcheck:
      test: 
        - CMD-SHELL
        - pg_isready
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  server:
    image: iic-test
    ports:
      - 80:80
    volumes:
      - ./cache:/usr/local/bin/cache
      - ./certs:/usr/local/bin/certs
      - ./templates:/usr/local/bin/templates
      - ./static:/usr/local/bin/static
      - ./Rocket.toml:/usr/local/bin/Rocket.toml
    environment:
      # datenbank
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@0.0.0.0:5431/${POSTGRES_DB}"
    env_file:
      - .env
    depends_on:
      - postgres



