version: '3'
services:
  db:
    image: postgres
    restart: always
    #env_file:
    #  - .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: 
        - CMD-SHELL
        - pg_isready
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - internal

  server:
    image: iic-release
    ports:
      - 8000:8000
    volumes:
      - ./cache:/usr/local/bin/cache
      - ./certs:/usr/local/bin/certs:ro
      - ./templates:/usr/local/bin/templates:ro
      - ./static:/usr/local/bin/static:ro
      - ./Rocket.toml:/usr/local/bin/Rocket.toml:ro
      - ./.env:/usr/local/bin/.env:ro
    environment:
      # datenbank
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    #env_file:
    #  - .env
    depends_on:
      - db
    networks: 
      - internal


networks: {internal: {}}
